name: Restyler
author: pbrisbin

inputs:
  mode:
    description: "summary-only|pull-request|push"
    default: "pull-request"
  fail:
    description: "Fail if differences were produced?"
    default: true
  image:
    description: "Restyled image to run"
    default: "restyled/restyler:edge"
  log-level:
    description: "Set restyler LOG_LEVEL"
    default: "info"
  github-token:
    description: "GitHub token for fetching PR details"
    default: ${{ github.token }}

outputs: {}

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        # Prepare
        cat > /tmp/event.json <<'EOM'
        ${{ github.event }}'
        EOM

    - shell: bash
      run: |
        # Run
        docker run --rm \
          --env LOG_LEVEL \
          --env LOG_COLOR=always \
          --env GITHUB_EVENT_JSON=/tmp/event.json \
          --env HOST_DIRECTORY="$PWD" \
          --env UNRESTRICTED=1 \
          --volume "$PWD":/code \
          --volume /tmp:/tmp \
          --volume /var/run/docker.sock:/var/run/docker.sock \
          --entrypoint restyle-path \
          "$IMAGE"
      env:
        IMAGE: ${{ inputs.image }}
        LOG_LEVEL: ${{ inputs.log-level }}
