name: Restyler
author: pbrisbin

inputs:
  image:
    description: "Restyled image to run"
    default: "restyled/restyler:edge"
  mode:
    description: "summary-only|pull-request|push"
    default: "pull-request"
  fail-on-differences:
    description: "Fail if differences were produced?"
    default: true
  log-level:
    description: "Set restyler LOG_LEVEL"
    default: "info"
  github-token:
    description: "GitHub token for fetching PR details"
    default: ${{ github.token }}

outputs: {}

runs:
  using: composite
  steps:
    # pre-conditions
    #   correct env?
    #   not excluded by labels?
    #   not excluded by author?

    # Determine changed files
    - id: prep
      shell: bash
      run: |
        # Determine added and modified files
        {
          echo 'changed<<EOM'
          gh api "/repos/$GH_REPO/pulls/$GH_PR/files" |
            jq '.[] | select(.status|test("^(added|modified)$")) | .filename' |
            tr '\n' ' '; echo
          echo 'EOM'
        } >>"$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_REPO: ${{ github.repository }}
        GH_PR: ${{ github.event.pull_request.number }}

    # Restyle changed files
    #   TODO: make commits

    - if: ${{ steps.prep.outputs.changed }}
      shell: bash
      run: |
        # Run restyler

        # Turn the quoted paths into a real (unquoted) array
        eval "changed=( $CHANGED )"

        docker run --rm \
          --env LOG_LEVEL \
          --env LOG_COLOR=always \
          --env HOST_DIRECTORY="$PWD" \
          --env UNRESTRICTED=1 \
          --volume "$PWD":/code \
          --volume /tmp:/tmp \
          --volume /var/run/docker.sock:/var/run/docker.sock \
          --entrypoint restyle-path \
          "$IMAGE" "${changed[@]}"
      env:
        IMAGE: ${{ inputs.image }}
        CHANGED: ${{ steps.prep.outputs.changed }}
        LOG_LEVEL: ${{ inputs.log-level }}

    # post-actions:
    #   print patch to build summary
    #   commit directly | open new PR | direct to summary
    #   option: fail if differences
