debug: true

tagFormat: "v0.${version}" # PVP prefixed

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets: "*-binaries/restyler-*.tar.gz"
      successComment: false

branches:
  - main
  - name: rc/*
    prerelease: '${name.replace(/^rc\//g, "rc-")}'
