tagFormat: "v0.${version}" # PVP prefixed

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
  - - "@semantic-release/github"
    - assets: "*-binaries/restyler-*.tar.gz"
      successCommentCondition: false

branches:
  - main
  - name: rc/*
    prerelease: '${name.replace(/^rc\//, "rc-")}'
