---
restylers:
  - stylish-haskell
  - brittany
  - prettier:
      include:
        - "**/*.yaml"
        - "**/*.yml"
  - hlint:
      include:
        - "**/*.hs"
        - "!src/Restyler/Config/ExpectedKeys.hs"
