---
remote_files:
  # yamllint disable-line rule:line-length
  - url: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/config/brittany/config.yaml
    path: brittany.yaml
  # yamllint disable-line rule:line-length
  - url: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/stylish-haskell.yaml
    path: .stylish-haskell.yaml
  # yamllint disable-line rule:line-length
  - url: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
    path: .hlint.yaml
restylers:
  - stylish-haskell
  - brittany
  - prettier:
      include:
        - "**/*.yaml"
        - "**/*.yml"
  - hlint
