enabled: false # TEMPORARY
restylers_version: dev
restylers:
  - whitespace
  # - hlint
  # - fourmolu
  # - stylish-haskell:
  #     enabled: false
  # - prettier:
  #     include:
  #       - "**/*.yaml"
  #       - "**/*.yml"
  # - "*"
