restylers_version: dev
restylers:
- hlint
- fourmolu
- stylish-haskell:
    enabled: false
- prettier:
    include:
      - "**/*.yaml"
      - "**/*.yml"
      - "**/.*.yaml"
      - "**/.*.yml"
- "*"
