---

# N.B. beta-testing with alternative default
branch_name: "restyled/{base}"

restylers:
  - stylish-haskell
  - brittany
  - prettier:
      include:
        - "**/*.yaml"
        - "**/*.yml"
  - hlint:
      include:
        - "**/*.hs"
        - "!src/Restyler/Config/ExpectedKeys.hs"
