name: Restyler
author: pbrisbin

inputs:
  image:
    default: "restyled/restyler:edge"
  github-token:
    default: ${{ github.token }}
  github-repository:
    default: ${{ github.repository }}

outputs: {}

runs:
  using: composite
  steps:
    - id: prep
      shell: bash
      run: |
        # Determine added and modified files
        {
          echo 'changed<<EOM'
          gh api "/repos/$GH_REPO/pulls/$GH_PR/files" |
            jq '.[] | select(.status|test("^(added|modified)$")) | .filename' |
            tr '\n' ' '; echo
          echo 'EOM'
        } >>"$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_REPO: ${{ github.repository }}
        GH_PR: ${{ github.event.pull_request.number }}

    - if: ${{ steps.prep.outputs.changed }}
      shell: bash
      run: |
        docker run --rm \
          --env LOG_COLOR=always \
          --env HOST_DIRECTORY="$PWD" \
          --env UNRESTRICTED=1 \
          --volume "$PWD":/code \
          --volume /tmp:/tmp \
          --volume /var/run/docker.sock:/var/run/docker.sock \
          --entrypoint restyle-path \
          "$IMAGE" $CHANGED
      env:
        IMAGE: ${{ inputs.image }}
        CHANGED: ${{ steps.prep.outputs.changed }}
