name: Restyler
author: pbrisbin

inputs:
  image:
    default: "restyled/restyler:main"
  github-token:
    default: ${{ github.token }}
  github-repository:
    default: ${{ github.repository }}

outputs: {}

runs:
  using: composite
  steps:
    - id: prep
      run: |
        # Determine added and modified files
        {
          echo 'changed<<EOM'
          gh api '/repos/freckle/megarepo/pulls/35126/files' |
            jq '.[] | select(.status|test("added|modified")) | .filename' |
            tr '\n' ' '; echo
          echo 'EOM'
        } >>"$GITHUB_OUTPUT"

    - if: ${{ steps.prep.outputs.changed }}
      run: |
        docker_run --interactive --rm \
          --env LOG_LEVEL \
          --env LOG_DESTINATION \
          --env LOG_FORMAT \
          --env LOG_COLOR \
          --env HOST_DIRECTORY="$PWD" \
          --env UNRESTRICTED=1 \
          --volume "$PWD":/code \
          --volume /tmp:/tmp \
          --volume /var/run/docker.sock:/var/run/docker.sock \
          --entrypoint restyle-path \
          '${{ inputs.image }}' ${{ steps.prep.outputs.changed }}
