name: restyler
version: 0.1.0.0
license: MIT

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

ghc-options:
  -Wall
  -Wcompat
  -Widentities
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wpartial-fields
  -Wredundant-constraints

dependencies:
  - base
  - rio


library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2
  dependencies:
    - Glob
    - aeson
    - aeson-casing
    - ansi-terminal
    - bytestring
    - conduit
    - directory
    - edit-distance
    - envparse
    - errors
    - fast-logger
    - filepath
    - github
    - http-client-tls
    - http-conduit
    - megaparsec
    - monad-logger
    - mtl
    - optparse-applicative
    - process
    - safe
    - safe-exceptions
    - scanner
    - shakespeare
    - temporary
    - text
    - unordered-containers
    - vector
    - yaml

executables:
  restyler:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - restyler

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - QuickCheck
      - bytestring
      - github
      - hspec
      - quickcheck-text
      - restyler
      - text
      - yaml
