name: restyler
version: 0.4.1.1
license: MIT

language: GHC2021

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - GADTs
  - LambdaCase
  - NoFieldSelectors
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoPostfixOperators
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - TypeFamilies

ghc-options:
  - -fignore-optim-changes
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - Blammo
    - Glob
    - aeson
    - aeson-casing
    - annotated-exception
    - barbies
    - bytestring
    - composition-extra
    - conduit
    - containers
    - directory
    - edit-distance
    - envparse
    - errata
    - errors
    - exceptions
    - extra
    - extra
    - file-embed
    - filepath
    - http-conduit
    - microlens
    - microlens-mtl
    - optparse-applicative
    - relude
    - semigroups
    - text
    - typed-process
    - unliftio
    - unliftio-core
    - unordered-containers
    - validation
    - vector
    - yaml

executables:
  restyle:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - restyler

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Blammo
      - QuickCheck
      - aeson
      - containers
      - directory
      - envparse
      - extra
      - filepath
      - hspec
      - hspec-core
      - hspec-expectations-lifted
      - lens-aeson
      - load-env
      - restyler
      - shakespeare
      - text
      - yaml
