---
name: restyler
version: "0.0.0"

# Dependencies shared in *all* targets
dependencies:
  - base

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2
  dependencies:
    - Glob
    - aeson
    - bytestring
    - directory
    - envparse
    - errors
    - filepath
    - github
    - http-client-tls
    - megaparsec
    - monad-logger
    - mtl
    - optparse-applicative
    - process
    - safe
    - safe-exceptions
    - shakespeare
    - temporary
    - text
    - unordered-containers
    - vector
    - yaml
  default-extensions:
    # I don't like putting extensions in the packaging and prefer to see them in
    # the modules where they are used. However, this extension must be here to
    # avoid forgetting it and nudge me to use Restyler.Prelude everywhere.
    - NoImplicitPrelude

executables:
  restyler:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - restyler

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - bytestring
      - directory
      - github
      - hspec
      - restyler
      - temporary
      - text
      - yaml
