name: restyler
version: 0.2.0.0
license: MIT

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

ghc-options:
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-import-lists
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - Blammo
    - Glob
    - aeson
    - aeson-casing
    - barbies
    - bytestring
    - composition-extra
    - conduit
    - containers
    - datadog
    - directory
    - edit-distance
    - envparse
    - errors
    - extra
    - file-embed
    - filepath
    - github
    - http-client-tls
    - http-conduit
    - megaparsec
    - microlens
    - microlens-mtl
    - optparse-applicative
    - process
    - relude
    - shakespeare
    - text
    - time
    - unliftio
    - unliftio-core
    - unordered-containers
    - validation
    - vector
    - word-wrap
    - yaml

executables:
  restyler:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - github
      - restyler
      - time
  restyle-path:
    main: main.hs
    source-dirs: restyle-path
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Blammo
      - envparse
      - restyler

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Blammo
      - QuickCheck
      - aeson
      - containers
      - directory
      - extra
      - filepath
      - github
      - hspec
      - hspec-core
      - hspec-expectations-lifted
      - lens-aeson
      - relude
      - restyler
      - shakespeare
      - text
      - yaml
