name: restyler
version: 0.0.0.0
license: AGPL-3

language: GHC2021

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - GADTs
  - LambdaCase
  - NoFieldSelectors
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoPostfixOperators
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - TypeFamilies

ghc-options:
  - -fignore-optim-changes
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-poly-kind-signatures
  - -Wno-missing-role-annotations
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - Blammo
    - Glob
    - aeson
    - aeson-casing
    - aeson-pretty
    - annotated-exception
    - autodocodec
    - autodocodec-yaml
    - composition-extra
    - conduit
    - errors
    - exceptions
    - extra
    - filepath
    - http-conduit
    - microlens
    - microlens-mtl
    - monad-logger-aeson
    - network-uri
    - opt-env-conf >= 0.6.0.2
    - path
    - relude
    - retry
    - ronn
    - ronn-opt-env-conf
    - safe-coloured-text
    - semigroups
    - text
    - typed-process
    - unliftio
    - unliftio-core
    - unordered-containers
    - validation
    - vector
    - yaml

executables:
  restyle:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - restyler

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Blammo
      - aeson
      - autodocodec
      - autodocodec-yaml
      - containers
      - directory
      - extra
      - filepath
      - hspec
      - hspec-core
      - hspec-expectations-lifted
      - lens-aeson
      - opt-env-conf
      - path
      - restyler
      - safe-coloured-text
      - text
      - typed-process
      - unliftio
      - yaml
