resolver: lts-23.11
extra-deps:
  - random-1.3.1

  - git: https://codeberg.org/pbrisbin/mdoc.git
    commit: a40f8178649a7e5ff0bf7dd3260359d164c8b90d

  # faint support
  - github: pbrisbin/prettyprinter
    commit: b1e625532566196f53f0a365a7ce76dc6310a54b
    subdirs:
      - prettyprinter-ansi-terminal

allow-newer: true
allow-newer-deps:
  - uuid-types
