steps:
  - label: Build
    command: |
      echo "--- Upgrade Stack"
      stack upgrade

      echo "--- Dependencies"
      make setup setup.lint

      echo "--- Build"
      make build

      echo "--- Test"
      make test

      echo "--- Lint"
      make lint
    plugins:
      - docker#v3.0.1:
          image: quay.io/haskell_works/stack-build-minimal
          environment:
            GIT_AUTHOR_EMAIL: ci@restyled.io
            GIT_AUTHOR_NAME: Restyled.io CI
            GIT_COMMITTER_EMAIL: ci@restyled.io
            GIT_COMMITTER_NAME: Restyled.io CI
            STACK_ARGUMENTS: --no-terminal
          working_dir: /code
          volumes:
            - '${BUILDKITE_BUILD_CHECKOUT_PATH}:/code'
            - '/cache/restyler/.stack-work:/code/.stack-work'
            - '/cache/stack:/root/.stack'

  - label: Image
    command: docker build --tag restyled/restyler .
    plugins:
      - docker#v3.0.1:
          image: restyled/ops
          volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'

  - wait

  - label: Release
    command: |
      echo "--- Pushing image to registry"
      docker tag restyled/restyler \
        quay.io/restyled-io/restyler:bk$BUILDKITE_BUILD_NUMBER
      docker login -u restyled-io+buildkite -p "$QUAY_DOCKER_PASSWORD" quay.io
      docker push quay.io/restyled-io/restyler:bk$BUILDKITE_BUILD_NUMBER

      echo "--- Setting up environment"
      # Unclear why this is required, but it is
      export HEROKU_EMAIL=$HEROKU_EMAIL
      export HEROKU_API_KEY=$HEROKU_API_KEY
      export PUSHOVER_API_KEY=$PUSHOVER_API_KEY
      export PUSHOVER_USER_KEY=$PUSHOVER_USER_KEY

      echo "--- Heroku config:set"
      heroku config:set --app restyled-io \
        "RESTYLER_IMAGE=quay.io/restyled-io/restyler" \
        "RESTYLER_TAG=bk$BUILDKITE_BUILD_NUMBER"

      notify "restyled-io[restyler]" "Deploy of bk$BUILDKITE_BUILD_NUMBER successful"
    branches: master
    plugins:
      - docker#v3.0.1:
          image: restyled/ops
          volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
