name: Agent

on:
  pull_request:

jobs:
  restyled:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: |
          # Install gh
          cd /tmp
          curl -L -sSf https://github.com/cli/cli/releases/download/v2.53.0/gh_2.53.0_linux_amd64.tar.gz | tar xzvf -
          sudo cp -v gh_*/bin/gh /usr/local/bin
        working-directory: /tmp

      - run: |
          # Set PR status pending
          gh api 'repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}' \
            -f state=pending \
            -f context=restyled

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: restyled-io/restyler/actions/setup@main
      - id: restyler
        uses: restyled-io/restyler/actions/run@main
        with:
          log-format: json
          committer-email: "commits@restyled.io"
          committer-name: "Restyled.io"
      - id: create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          base: ${{ steps.restyler.outputs.restyled-base }}
          branch: ${{ steps.restyler.outputs.restyled-head }}
          title: ${{ steps.restyler.outputs.restyled-title }}
          body: ${{ steps.restyler.outputs.restyled-body }}
          labels: ${{ steps.restyler.outputs.restyled-labels }}
          reviewers: ${{ steps.restyler.outputs.restyled-reviewers }}
          team-reviewers: ${{ steps.restyler.outputs.restyled-team-reviewers }}
          delete-branch: true

      # Skipped
      - if: |
          steps.restyler.outputs.differences == 'false' &&
          steps.restyler.outputs.skipped == 'true'
        run: |
          # Set PR status success
          gh api 'repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}' \
            -f state=success \
            -f description="Restyling skipped" \
            -f context=restyled

      # No differences
      - if: |
          steps.restyler.outputs.differences != 'true' &&
          steps.restyler.outputs.skipped != 'true'
        run: |
          # Set PR status success
          gh api 'repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}' \
            -f state=success \
            -f description="No differences" \
            -f context=restyled

      # Differences
      - if: |
          steps.restyler.outputs.differences == 'true' &&
          steps.restyler.outputs.skipped != 'true'
        run: |
          # Set PR status failure
          gh api 'repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}' \
            -f state=failure \
            -f target_url=${{ steps.create-pull-request.outputs.pull-request-url }} \
            -f description="Restyled found differences" \
            -f context=restyled

      # Error
      - if: ${{ failure() }}
        run: |
          # Set PR status error
          gh api 'repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}' \
            -f state=error \
            -f description="Restyled errored" \
            -f context=restyled
