name: Agent

on:
  pull_request:

jobs:
  restyled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: restyled-io/restyler/actions/setup@main
      - id: restyler
        uses: restyled-io/restyler/actions/run@main
        with:
          log-format: json
          committer-email: "commits@restyled.io"
          committer-name: "Restyled.io"
      - id: create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          base: ${{ steps.restyler.outputs.restyled-base }}
          branch: ${{ steps.restyler.outputs.restyled-head }}
          title: ${{ steps.restyler.outputs.restyled-title }}
          body: ${{ steps.restyler.outputs.restyled-body }}
          labels: ${{ steps.restyler.outputs.restyled-labels }}
          reviewers: ${{ steps.restyler.outputs.restyled-reviewers }}
          team-reviewers: ${{ steps.restyler.outputs.restyled-team-reviewers }}
          delete-branch: true

      # TODO: set "restyled" PR status
