name: Restyler
author: pbrisbin

inputs:
  log-level:
    description: "LOG_LEVEL"
    default: "info"
  github-token:
    description: "GITHUB_TOKEN"
    default: ${{ github.token }}
  create-pull-request:
    description: "Create/update a Restyled PR?"
    default: true
  fail-if-differences-found:
    description: "Fail if differences are found?"
    default: true
  committer-name:
    description: "Name used for Restyled commits"
    default: "Restyled.io"
  committer-email:
    description: "Email used for Restyled commits"
    default: "commits@restyled.io"

outputs:
  differences:
    description: "'true' if restyling produced differences"
    value: ${{ steps.restyler.outputs.differences }}
  restyled-pr-number:
    description: "Number of the Restyled PR, if it exists"
    value: ${{ steps.create-pull-request.outputs.pull-request-number }}
  restyled-pr-url:
    description: "URL to the Restyled PR, if it exists"
    value: ${{ steps.create-pull-request.outputs.pull-request-url }}
  restyled-pr-operation:
    description: "Operation performed with the Restyled PR: created, updated, or closed"
    value: ${{ steps.create-pull-request.outputs.pull-request-operation }}
  restyled-pr-head-sha:
    description: "Head SHA of the Restyled PR, if it exists"
    value: ${{ steps.create-pull-request.outputs.pull-request-head-sha }}
  restyled-pr-branch:
    description: "Branch of the Restyled PR, if it exists"
    value: ${{ steps.create-pull-request.outputs.pull-request-branch }}

runs:
  using: composite
  steps:
    - id: restyler
      shell: bash
      run: |
        restyle-gha --pr '${{github.repository }}#${{ github.event.pull_request.number }}'
      env:
        # For env-based options
        GITHUB_TOKEN: ${{ github.token }}
        LOG_BREAKPOINT: 200
        LOG_COLOR: always
        LOG_LEVEL: ${{ inputs.log-level }}
        RESTYLER_NO_CAP_DROP_ALL: x

    - id: create-pull-request
      if: |
        inputs.create-pull-request &&
        steps.restyler.outputs.differences == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.github-token }}
        base: ${{ steps.restyler.outputs.restyled-base }}
        branch: ${{ steps.restyler.outputs.restyled-head }}
        title: ${{ steps.restyler.outputs.restyled-title }}
        body: ${{ steps.restyler.outputs.restyled-body }}
        labels: ${{ steps.restyler.outputs.restyled-labels }}
        reviewers: ${{ steps.restyler.outputs.restyled-reviewers }}
        team-reviewers: ${{ steps.restyler.outputs.restyled-team-reviewers }}
        delete-branch: true

      GIT_AUTHOR_EMAIL: ${{ inputs.committer-email }}
      GIT_AUTHOR_NAME: ${{ inputs.committer-name }}
      GIT_COMMITTER_EMAIL: ${{ inputs.committer-email }}
      GIT_COMMITTER_NAME: ${{ inputs.committer-name }}

    - if: |
        inputs.fail-if-differences-found == 'true' &&
        steps.restyler.outputs.differences == 'true'
      run: |
        echo "Restyling produced differences" >&2
        exit 1
