name: Restyler
author: pbrisbin

inputs:
  binary:
    description: "Restyler binary to run"
    required: true
  log-level:
    description: "Set restyler LOG_LEVEL"
    default: "info"
  github-token:
    description: "GitHub token for fetching PR details"
    default: ${{ github.token }}

outputs:
  differences:
    description: ""
    value: ${{ steps.restyler.outputs.differences }}
  restyled-base:
    description: ""
    value: ${{ steps.restyler.outputs.restyled-base }}
  restyled-head:
    description: ""
    value: ${{ steps.restyler.outputs.restyled-head }}
  restyled-title:
    description: ""
    value: ${{ steps.restyler.outputs.restyled-title }}
  restyled-body:
    description: ""
    value: ${{ steps.restyler.outputs.restyled-body }}
  restyled-labels:
    description: ""
    value: ${{ steps.restyler.outputs.restyled-labels }}
  restyled-reviewers:
    description: ""
    value: ${{ steps.restyler.outputs.restyled-reviewers }}
  restyled-team-reviewers:
    description: ""
    value: ${{ steps.restyler.outputs.restyled-team-reviewers }}
  pull-request-number:
    description: ""
    value: ${{ steps.create-pull-request.outputs.pull-request-number }}
  pull-request-url:
    description: ""
    value: ${{ steps.create-pull-request.outputs.pull-request-url }}
  pull-request-operation:
    description: ""
    value: ${{ steps.create-pull-request.outputs.pull-request-operation }}
  pull-request-head-sha:
    description: ""
    value: ${{ steps.create-pull-request.outputs.pull-request-head-sha }}
  pull-request-branch:
    description: ""
    value: ${{ steps.create-pull-request.outputs.pull-request-branch }}

runs:
  using: composite
  steps:
    - id: restyler
      shell: bash
      run: |
        $RESTYLER_BINARY --pr '${{github.repository }}#${{ github.event.pull_request.number }}'
      env:
        # For passing to run
        RESTYLER_BINARY: ${{ inputs.binary }}

        # For env-based options
        GITHUB_TOKEN: ${{ github.token }}
        LOG_BREAKPOINT: 200
        LOG_COLOR: always
        LOG_LEVEL: ${{ inputs.log-level }}
        RESTYLER_NO_CAP_DROP_ALL: x

    - id: create-pull-request
      if: ${{ steps.restyler.outputs.differences == 'true' }}
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.github-token }}
        base: ${{ steps.restyler.outputs.restyled-base }}
        branch: ${{ steps.restyler.outputs.restyled-head }}
        title: ${{ steps.restyler.outputs.restyled-title }}
        body: ${{ steps.restyler.outputs.restyled-body }}
        labels: ${{ steps.restyler.outputs.restyled-labels }}
        reviewers: ${{ steps.restyler.outputs.restyled-reviewers }}
        team-reviewers: ${{ steps.restyler.outputs.restyled-team-reviewers }}
        delete-branch: true

      GIT_AUTHOR_EMAIL: commits@restyled.io
      GIT_AUTHOR_NAME: Restyled.io
      GIT_COMMITTER_EMAIL: commits@restyled.io
      GIT_COMMITTER_NAME: Restyled.io

    - if: ${{ steps.restyler.outputs.differences == 'true' }}
      run: |
        echo "Restyling produced differences" >&2
        exit 1
