name: Setup the Restyler CLI
author: pbrisbin

inputs:
  tag:
    required: false

outputs: {}

runs:
  using: composite
  steps:
    - shell: bash
      working-directory: /tmp
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/restyled-io/restyler/main/install |
          sudo sh -s -- -t "$TAG"
      env:
        TAG: ${{ inputs.tag }}
