name: Setup the Restyler CLI
author: pbrisbin

inputs:
  version:
    default: "v0.3.0.0"

outputs: {}

runs:
  using: composite
  steps:
    - shell: bash
      run: |
         curl -sSf -O -L "https://github.com/restyled-io/restyler/releases/download/$INPUTS_VERSION/restyle-gha"
         chmod +x restyle-gha
         sudo mv -v restyle-gha /usr/local/bin
      env:
        INPUTS_VERSION: ${{ inputs.version }}
