name: Restyled

on:
  pull_request:

jobs:
  restyled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: restyled-io/restyler/actions/setup@main
      - id: restyler
        uses: restyled-io/restyler/actions/run@main
      - uses: peter-evans/create-pull-request@v6
        with:
          base: ${{ steps.restyler.outputs.restyled-base }}
          branch: ${{ steps.restyler.outputs.restyled-head }}
          title: ${{ steps.restyler.outputs.restyled-title }}
          body: ${{ steps.restyler.outputs.restyled-body }}
          labels: ${{ steps.restyler.outputs.restyled-labels }}
          reviewers: ${{ steps.restyler.outputs.restyled-reviewers }}
          team-reviewers: ${{ steps.restyler.outputs.restyled-team-reviewers }}
          delete-branch: true
      - if: ${{ steps.restyler.differences == 'true' }}
        name: Print Restyled differences
        run: |
          echo "Restyled found differences:"
          cat <<'EOM'
          ${{ steps.restyler.git-patch }}
          EOM
          exit 1
